name: Build and Test libCZI-vcpkg

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test_on_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: run tests on Windows-x64
        shell: bash
        run: |
          bash ./run_tests.sh

  test_on_linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: run tests on Linux-x64
        shell: bash
        run: |
          bash ./run_tests.sh
